[package]
name = "ferropipe-audit"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web server framework
axum = "0.7"
async-openai = "0.29"
tokio = { version = "1.0", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace"] }
shuttle-runtime = "0.41"
shuttle-axum    = "0.41"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "migrate"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

# HTTP client
reqwest = { version = "0.11", features = ["json"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Environment variables
dotenvy = "0.15"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Cargo integration
cargo_metadata = "0.18"
syn = { version = "2.0", features = ["full", "parsing", "visit"] }

# File system operations
walkdir = "2.0"
tempfile = "3.0"

# Git operations
git2 = "0.18"

# TOML parsing
toml = "0.8"

# Regex for pattern matching
regex = "1.0"

# Additional dependencies for syn
proc-macro2 = "1.0"
quote = "1.0"

# Process execution
tokio-process = "0.2"

# Additional JSON handling
json = "0.12"

# Additional dependencies for which crate
which = "4.4"

# For resolving the home directory
home = "0.5" 